### ISSUE TITLE
Module not being found when installed trough NPM

### ISSUE THREAD

**Issue by JustJollyJonah** [wermerb/ngx-trumbowyg#4]
Hello,

As of version 6.0.2 installing trough NPM in a fresh install results in the module not being found by angular whatever we try. I compared the two versions with a diff tool and you seem to have moved the lib folder from the root of the package to src/lib which seems to be causing the issue.

**Comment by wermerb** [comment]
Hi,

I will be able to check on this tonight. Thank you for the info.

**Comment by wermerb** [comment]
You should be able to import the module with new version:
`import { NgxTrumbowygModule } from 'ngx-trumbowyg';`
