### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'events' of null

### ISSUE THREAD

**Issue by theCrius** [wermerb/ngx-trumbowyg#6]
Immediately on load of the components that use this directive, the console report this error.

Details:

- Angular 6.0.5
- jquery 3.3.1
- trumbowyg 2.11.1
- ngx-trumbowyg 6.0.5

**Comment by wermerb** [comment]
Could you please provide a sample of your module configuration. I cannot reproduce this issue.

**Comment by theCrius** [comment]
Sorry, had to move fast and choosen a different wyswyg.
