### ISSUE TITLE
Add image error

### ISSUE THREAD

**Issue by benincasantonio** [wermerb/ngx-trumbowyg#7]
This is a gif of my problem:

![ice_video_20181116-111557](https://user-images.githubusercontent.com/16473620/48615421-30058d00-e991-11e8-86dd-d7343d913c84.gif)

And this is the code of the options 
`this.editorOptions = {
      lang: this.lang,
      svgPath: '/assets/trumbowyg/icons.svg',
      removeformatPasted: true,
      autogrow: true,
      btns: [
        ['viewHTML'],
        ['undo', 'redo'],
        ['formatting'],
        ['strong', 'em', 'del'],
        ['superscript', 'subscript'],
        ['link'],
        ['insertImage'],
        ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
        ['unorderedList', 'orderedList'],
        ['horizontalRule'],
        ['removeformat'],
        ['fullscreen']
      ],
    };`

**Comment by wermerb** [comment]
I don't think this is a bug. Your url is not pointing to an image.

**Comment by benincasantonio** [comment]
> I don't think this is a bug. Your url is not pointing to an image.


This is a more detailed video of the bug

https://youtu.be/LXTus1yoEUk

**Comment by wermerb** [comment]
There is something wrong with the youtube link I can't watch it. 
However I tried your issue in the demo app with the following url: https://picsum.photos/200/300 and it loads the image for me.

**Comment by benincasantonio** [comment]
> There is something wrong with the youtube link I can't watch it.
> However I tried your issue in the demo app with the following url: https://picsum.photos/200/300 and it loads the image for me.

I'm sorry, now the video is visible

**Comment by wermerb** [comment]
![editor](https://user-images.githubusercontent.com/7500717/48866956-e378e200-edd4-11e8-97ae-b6380cc792f4.gif)

@benincasantonio I cannot reproduce your issue.

**Comment by benincasantonio** [comment]
Problem solved!
it was enough to update the dependencies!!
